INSERT INTO FULL_NAME (ID, FIRST_NAME, LAST_NAME)
VALUES (10, 'JOHN', 'DOE');

INSERT INTO FULL_NAME (ID, FIRST_NAME, LAST_NAME)
VALUES (12, 'JOSHUA', 'BLOSH');

INSERT INTO AUTHOR (ID, FULL_NAME_ID)
VALUES (10, 10);

INSERT INTO AUTHOR (ID, FULL_NAME_ID)
VALUES (12, 12);

INSERT INTO BOOK (ISBN, AUTHOR_ID, PRICE, DESCRIPTION, STOCK)
VALUES ('1234567890123', 10, 29.99, 'A SAMPLE BOOK', 10);
