DELETE FROM BOOK;
DELETE FROM AUTHOR;
DELETE FROM CUSTOMER;
DELETE FROM FULL_NAME;


INSERT INTO FULL_NAME (ID, FIRST_NAME, LAST_NAME)
VALUES (10, 'JOHN', 'DOE');

INSERT INTO FULL_NAME (ID, FIRST_NAME, LAST_NAME)
VALUES (12, 'JOSHUA', 'BLOSH');

INSERT INTO AUTHOR (ID, FULL_NAME_ID)
VALUES (10, 10);

INSERT INTO AUTHOR (ID, FULL_NAME_ID)
VALUES (12, 12);

INSERT INTO BOOK (ISBN, AUTHOR_ID, PRICE, DESCRIPTION, STOCK)
VALUES ('9780306406157', 10, 29.99, 'A SAMPLE BOOK', 10);
